### ISSUE TITLE
Not able to launch Envision

### ISSUE THREAD

**Issue by radaniba** [marklogic-community/envision#135]
*### Welcome Envision enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem: Testing Envision on my localhost (macOS) but unable to get it starting

What behavior are you expecting?

What are the steps to reproduce the issue:
1) Updated my ML to 5.2.5
2) Tested it is working properly
3) my ML server version is 10

#### Tech details

Which Operating System are you using? macOS 

Which version of MarkLogic are you using? 10

Which version of the Data Hub are you using? 5.2.5

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  `java -jar envision.jar -d > myoutput.txt`

```
Starting. Please wait...

envName: local
modelsDir: (path_removed)/conceptConnectorModels
Installing Envision Modules...

11:30:49.352 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.RuntimeException: Caught exception before writing was completed: Local message: failed to apply resource at documents: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.ext.batch.DefaultWriteListener.afterCompletion(DefaultWriteListener.java:22)
        at com.marklogic.client.ext.batch.BatchWriterSupport.waitForCompletion(BatchWriterSupport.java:47)
        at com.marklogic.client.ext.batch.RestBatchWriter.waitForCompletion(RestBatchWriter.java:87)
        at com.marklogic.client.ext.file.GenericFileLoader.loadFiles(GenericFileLoader.java:79)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.loadAssets(DefaultModulesLoader.java:366)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.loadModules(DefaultModulesLoader.java:176)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.loadModules(DefaultModulesLoader.java:153)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.loadModules(DefaultModulesLoader.java:165)
        at com.marklogic.envision.commands.DeployEnvisionModulesCommand.execute(DeployEnvisionModulesCommand.java:45)
        at com.marklogic.appdeployer.impl.AbstractAppDeployer.executeCommand(AbstractAppDeployer.java:101)
        at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:85)
        at com.marklogic.envision.installer.InstallService.install(InstallService.java:47)
        at com.marklogic.grove.boot.ApplicationRunListener.started(ApplicationRunListener.java:33)
        at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:71)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
        at com.marklogic.grove.boot.Application.main(Application.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4395)
        at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3467)
        at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3547)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:54)
        at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:80)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by paxtonhare** [comment]
I'm about to update the docs with this info:


On first run Envision will install its modules into your DHF modules database. This happens before Envision tries to read your hub configuration. If you are using non-standard ports you'll need to make a few changes to an application.properties file. Simply create application.properties next to envision.jar.

```properties
# Change these as needed
marklogic.username=admin
marklogic.password=admin
marklogic.port=8011
marklogic.managePort=8002
marklogic.adminPort=8001
```

Does that fix it for you?

**Comment by radaniba** [comment]
Thank you so much @paxtonhare that fixed my problem indeed
